x-restart-policy: &restart_policy
  restart: unless-stopped
  pull_policy: always
volumes:
  job_log:
services:
  xxl-job:
    container_name: 'xxl-job'
    image: xuxueli/xxl-job-admin:2.4.1
    environment:
      TZ: Asia/Shanghai
      PARAMS: "--spring.datasource.url=jdbc:mysql://localhost:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=lq_job --spring.datasource.password=liangqing365"
    <<: *restart_policy
    mem_limit: 2G
    ports:
      - "8181:8080"
    volumes:
      - job_log:/data
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "3"
    networks:
      - xxl_job_net
networks:
   xxl_job_net:
    driver: bridge