x-restart-policy: &restart_policy
  restart: unless-stopped
  pull_policy: always
volumes:
  redis_data:
services:
  redis:
    container_name: 'redis'
    image: redis
    environment:
      TZ: Asia/Shanghai
    <<: *restart_policy
    mem_limit: 2G
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: "--requirepass 123456"
